# Site settings
title: kmckiern
url: http://www.kmckiern.github.io
twitter_username: k_mckiern
github_username: kmckiern
linkedin_username: keri-mckiernan
google_analytics: UA-107176365-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

