# Site settings
title: kmckiern
description: "my website"
url: http://www.kmckiern.github.io
github_username: kmckiern
twitter_username: keri_mckiernan
google_analytics: UA-107176365-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

