# Site settings
title: Keri A. McKiernan
url: http://www.kmckiern.github.io
twitter_username: k_mckiern
github_username:  kmckiern
google_analytics: UA-107176365-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

