# Site settings
title: kmckiern
description: "personal website of Keri McKiernan"
url: http://www.kmckiern.github.io
github_username: kmckiern
twitter_username: k_mckiern
linkedin_username: keri-mckiernan
google_analytics: UA-107176365-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

